# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f730673a09289e07e407077c9b2bf50928c8de74c19c864abe62f25caa77cf2ce4d0b6b00a36818f7dbf3855e9cc21223dc2533217633cf78ba78f505a030a7

test:
  secret_key_base: 37b1bd9f7ab47aec599e893459c56af65dba6fab54bcf3a3f3db61621557bbc14b77cbac5bb8ba8eb6ddb246c2c51e02eb28b2c7a55b912b317f3388d6ed257d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
